//
//  MainRouter.swift
//  DevExam
//
//  Created by Vlad Ralovich on 8.03.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

 protocol MainRoutingLogic
{
    func routeToDetailVC(indexPath: IndexPath)
}

protocol MainDataPassing
{
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  // MARK: Routing
  
  func routeToDetailVC(indexPath: IndexPath)
  {
      let destinationVC = DetailViewController(data: dataStore!.list[indexPath.row])
      navigateToSomewhere(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: MainViewController, destination: DetailViewController)
  {
      source.navigationController?.pushViewController(destination, animated: true)
  }
}
