//
//  SingInRouter.swift
//  DevExam
//
//  Created by Vlad Ralovich on 7.03.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SingInRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SingInDataPassing
{
  var dataStore: SingInDataStore? { get }
}

class SingInRouter: NSObject, SingInRoutingLogic, SingInDataPassing
{
  weak var viewController: SingInViewController?
  var dataStore: SingInDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    
      let mainVC = MainViewController()
      let destinationVC = UINavigationController(rootViewController: mainVC)
      destinationVC.modalPresentationStyle = .fullScreen
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: SingInViewController, destination: UIViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SingInDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
