//
//  SingInModels.swift
//  DevExam
//
//  Created by Vlad Ralovich on 7.03.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SingIn
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        enum RequestType {
            case getPhoneMask
        }
    }
    struct Response
    {
        enum ResponseType {
            case pesentPhoneMask(_ : PhoneMaskModel)
        }
    }
    struct ViewModel
    {
        enum viewModelData {
            case currentPhoneMask(_ : PhoneMaskModel)
        }
    }
  }
}
