//
//  SingInViewController.swift
//  DevExam
//
//  Created by Vlad Ralovich on 7.03.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SingInDisplayLogic: AnyObject
{
  func displaySomething(viewModel: SingIn.Something.ViewModel)
}

class SingInViewController: UIViewController, SingInDisplayLogic
{
  var interactor: SingInBusinessLogic?
  var router: (NSObjectProtocol & SingInRoutingLogic & SingInDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SingInInteractor()
    let presenter = SingInPresenter()
    let router = SingInRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
    doSomething()
    view.backgroundColor = .cyan
  }
  
  // MARK: Do something
  
    private let loginTextField = UITextField()
    private let passwordTextField = UITextField()
    private let singInButton = UIButton()
    
    private func setupUI() {
        loginTextField.translatesAutoresizingMaskIntoConstraints = false
        passwordTextField.translatesAutoresizingMaskIntoConstraints = false
        singInButton.translatesAutoresizingMaskIntoConstraints = false
        
        view.addSubview(loginTextField)
        view.addSubview(passwordTextField)
        view.addSubview(singInButton)
        let guide = view.safeAreaLayoutGuide
        
        NSLayoutConstraint.activate([
            loginTextField.topAnchor.constraint(equalTo: guide.topAnchor, constant: 32),
            loginTextField.leftAnchor.constraint(equalTo: guide.leftAnchor, constant: 16),
            loginTextField.rightAnchor.constraint(equalTo: guide.rightAnchor, constant: -16),
            
            passwordTextField.topAnchor.constraint(equalTo: loginTextField.bottomAnchor, constant: 16),
            passwordTextField.leftAnchor.constraint(equalTo: guide.leftAnchor, constant: 16),
            passwordTextField.rightAnchor.constraint(equalTo: guide.rightAnchor, constant: -16),
            
            singInButton.topAnchor.constraint(equalTo: passwordTextField.bottomAnchor, constant: 32),
            singInButton.widthAnchor.constraint(equalToConstant: 100),
            singInButton.centerXAnchor.constraint(equalTo: guide.centerXAnchor)
        ])
        
        loginTextField.placeholder = "loginTextField"
        passwordTextField.placeholder = "passwordTextField"
        singInButton.backgroundColor = .brown
    }
    
  func doSomething()
  {
    let request = SingIn.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SingIn.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
